version: '3'
services:
  web:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: production
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
